version: 2.1

orbs:
  aws_assume_role: lbh-hackit/aws_assume_role@0.1.0

executors:
  docker-python:
    docker:
      - image: cimg/python:3.12
  docker-terraform:
    docker:
      - image: "hashicorp/terraform:1.1.9"
  docker-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

references:
  workspace_root: &workspace_root "~"
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

commands:
  assume-role-and-persist-workspace:
    description: "Assumes deployment role and persists credentials across jobs"
    parameters:
      aws-account:
        type: string
    steps:
      - checkout
      - aws_assume_role/assume_role:
          account: <<parameters.aws-account>>
          profile_name: default
          role: "LBH_Circle_CI_Deployment_Role"
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-init-then-plan:
    description: "Initializes and run plan from terraform configuration"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform get -update=true
            terraform init
          name: get and init
      - run:
          name: plan
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform plan -out=plan.out
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
            - project/*
  terraform-compliance:
    description: "Run Terraform Compliance checks"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          command: |
            cd ./terraform/<<parameters.environment>>/
            apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
            apk add --update --no-cache g++ gcc libxslt-dev python3-dev
            python3 -m ensurepip
            pip3 install --no-cache --upgrade pip setuptools
            pip install terraform-compliance
            terraform-compliance -f terraform-compliance/ -p plan.out
          name: terraform compliance
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  terraform-apply:
    description: "Runs Terraform Apply"
    parameters:
      environment:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: apply
          command: |
            cd ./terraform/<<parameters.environment>>/
            terraform apply -auto-approve plan.out
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .aws
  deploy-lambda:
    description: "Deploys via Serverless"
    parameters:
      stage:
        type: string
    steps:
      - *attach_workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | bash -
            apt-get update && apt-get install -y nodejs
      - run:
          name: Install serverless CLI
          command: npm i -g serverless
      - run:
          name: Build lambda
          command: |
            cd ./CautionaryAlertsListener/
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Deploy lambda
          command: |
            cd ./CautionaryAlertsListener/
            sls deploy --stage <<parameters.stage>> --conceal

jobs:
  assume-role-disaster-recovery:
    executor: docker-python
    steps:
      - assume-role-and-persist-workspace:
          aws-account: $AWS_ACCOUNT_DISASTER_RECOVERY
  terraform-init-and-plan-disaster-recovery:
    executor: docker-terraform
    steps:
      - terraform-init-then-plan:
          environment: "production"
  terraform-compliance-disaster-recovery:
    executor: docker-terraform
    steps:
      - terraform-compliance:
          environment: "production"
  terraform-apply-disaster-recovery:
    executor: docker-terraform
    steps:
      - terraform-apply:
          environment: "production"
  deploy-to-disaster-recovery:
    executor: docker-dotnet
    steps:
      - deploy-lambda:
          stage: "production"

workflows:
  check-and-deploy-staging-and-production:
      jobs:
      - permit-production-terraform-release:
          type: approval
      - assume-role-disaster-recovery:
          context: api-assume-role-disaster-recovery-context
          requires:
              - permit-production-terraform-release
          filters:
             branches:
               only: disaster-recovery-test
      - terraform-init-and-plan-disaster-recovery:
          requires:
            - assume-role-disaster-recovery
          filters:
            branches:
              only: disaster-recovery-test
      - terraform-compliance-disaster-recovery:
          requires:
            - terraform-init-and-plan-disaster-recovery
          filters:
            branches:
              only: disaster-recovery-test
      - terraform-apply-disaster-recovery:
          requires:
            - terraform-compliance-disaster-recovery
          filters:
            branches:
              only: disaster-recovery-test
      - permit-disaster-recovery-release:
          type: approval
          requires:
            - deploy-to-staging
            - terraform-apply-disaster-recovery
          filters:
            branches:
              only: disaster-recovery-test
      - deploy-to-disaster-recovery:
          context:
            - api-nuget-token-context
            - "Serverless Framework"
          requires:
            - permit-disaster-recovery-release
          filters:
            branches:
              only: disaster-recovery-test
